tasks:
  - name: Setup fnm (Fast node manager)
    before: curl -fsSL https://fnm.vercel.app/install | bash
    init: |
      source /home/gitpod/.bashrc
      fnm install --latest
  - name: Setup libheif
    before: sudo apt update
    init: |
      sudo apt install -y libheif-dev
  - name: Setup nomia
    init: npm install --location=global npm@latest typescript@latest markdownlint-cli@latest 
  - name: Setup nomia
    init: npm install
  - name: Start typecript service
    command: npm run dev
    openMode: tab-after
